"""empty message

Revision ID: 1ba46280f27d
Revises: c8bad06b9d98
Create Date: 2018-08-14 10:31:01.636052

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ba46280f27d'
down_revision = 'c8bad06b9d98'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ithriv_user', sa.Column('role', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ithriv_user', 'role')
    # ### end Alembic commands ###
