"""empty message

Revision ID: 308fb31d7ed7
Revises: e90fc725c5ab
Create Date: 2018-07-09 15:55:52.108974

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '308fb31d7ed7'
down_revision = 'e90fc725c5ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('availability', 'viewable')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('availability', sa.Column('viewable', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
