"""empty message

Revision ID: 43a24a9c13b7
Revises: 0381e8902180
Create Date: 2018-08-06 14:56:37.035552

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43a24a9c13b7'
down_revision = '0381e8902180'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ithriv_user', sa.Column('email_verified', sa.Boolean(), nullable=False, server_default=sa.false()))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ithriv_user', 'email_verified')
    # ### end Alembic commands ###
