"""empty message

Revision ID: 4a97b5eabce9
Revises: f5f2595105c1
Create Date: 2018-05-21 18:55:26.301295

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a97b5eabce9'
down_revision = 'f5f2595105c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('category', sa.Column('icon', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('category', 'icon')
    # ### end Alembic commands ###
