"""empty message

Revision ID: 4ba139a7fa04
Revises: ab85e948d8c0
Create Date: 2018-06-27 14:40:32.617642

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ba139a7fa04'
down_revision = 'ab85e948d8c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('category', sa.Column('icon_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'category', 'icon', ['icon_id'], ['id'])
    op.drop_column('category', 'icon')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('category', sa.Column('icon', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'category', type_='foreignkey')
    op.drop_column('category', 'icon_id')
    # ### end Alembic commands ###
