"""empty message

Revision ID: 4d934a9a222a
Revises: 4d95876e289c
Create Date: 2018-09-13 15:05:04.633219

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d934a9a222a'
down_revision = '4d95876e289c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('institution', sa.Column('hide_availablity', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('institution', 'hide_availablity')
    # ### end Alembic commands ###
