"""empty message

Revision ID: 4d95876e289c
Revises: 31366d36a716
Create Date: 2018-09-01 15:44:30.653405

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d95876e289c'
down_revision = '31366d36a716'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ithriv_user', 'uid')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ithriv_user', sa.Column('uid', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
