"""empty message

Revision ID: 7974a6660a3a
Revises: 997fe0d76ad2
Create Date: 2018-11-01 15:30:26.491128

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7974a6660a3a'
down_revision = '997fe0d76ad2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('category', sa.Column('display_order', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('category', 'display_order')
    # ### end Alembic commands ###
