"""empty message

Revision ID: 7e3f25efcfb9
Revises: 43a24a9c13b7
Create Date: 2018-08-09 13:58:20.672223

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e3f25efcfb9'
down_revision = '43a24a9c13b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ithriv_user', sa.Column('institution_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'ithriv_user', 'institution', ['institution_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'ithriv_user', type_='foreignkey')
    op.drop_column('ithriv_user', 'institution_id')
    # ### end Alembic commands ###
