"""empty message

Revision ID: 80c640f1a81b
Revises: ca41dade86d0
Create Date: 2018-03-30 13:57:07.857571

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80c640f1a81b'
down_revision = 'ca41dade86d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('institution',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('resource', sa.Column('institution_id', sa.Integer(), nullable=True))
    op.add_column('resource', sa.Column('type_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'resource', 'type', ['type_id'], ['id'])
    op.create_foreign_key(None, 'resource', 'institution', ['institution_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'resource', type_='foreignkey')
    op.drop_constraint(None, 'resource', type_='foreignkey')
    op.drop_column('resource', 'type_id')
    op.drop_column('resource', 'institution_id')
    op.drop_table('type')
    op.drop_table('institution')
    # ### end Alembic commands ###
