"""empty message

Revision ID: 846cfa5ebac5
Revises: 8d10371bc8f5
Create Date: 2018-07-20 09:25:30.587211

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '846cfa5ebac5'
down_revision = '8d10371bc8f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('resource', 'approved',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('resource', 'approved',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
