"""empty message

Revision ID: 8638819b740c
Revises: 74f2bccb1af4
Create Date: 2018-06-12 08:37:54.016560

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8638819b740c'
down_revision = '74f2bccb1af4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('category', sa.Column('brief_description', sa.String(), nullable=True))
    op.add_column('category', sa.Column('color', sa.String(), nullable=True))
    op.add_column('category', sa.Column('image', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('category', 'image')
    op.drop_column('category', 'color')
    op.drop_column('category', 'brief_description')
    # ### end Alembic commands ###
