"""empty message

Revision ID: 8a0e295af33c
Revises: 308fb31d7ed7
Create Date: 2018-07-10 11:38:42.967177

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a0e295af33c'
down_revision = '308fb31d7ed7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resource', sa.Column('cost', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('resource', 'cost')
    # ### end Alembic commands ###
