"""empty message

Revision ID: 997fe0d76ad2
Revises: 4d95876e289c
Create Date: 2018-09-17 13:22:02.389302

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '997fe0d76ad2'
down_revision = '4d95876e289c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('institution', sa.Column('hide_availability', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('institution', 'hide_availability')
    # ### end Alembic commands ###
