"""empty message

Revision ID: bed398ab90b5
Revises: df7e4df7d800
Create Date: 2018-08-29 17:16:51.360573

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bed398ab90b5'
down_revision = 'df7e4df7d800'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('institution', sa.Column('domain', sa.String(), nullable=True))
    op.add_column('ithriv_user', sa.Column('eppn', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ithriv_user', 'eppn')
    op.drop_column('institution', 'domain')
    # ### end Alembic commands ###
