"""empty message

Revision ID: c8bad06b9d98
Revises: 7e3f25efcfb9
Create Date: 2018-08-13 13:18:39.083131

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c8bad06b9d98'
down_revision = '7e3f25efcfb9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('type', sa.Column('icon_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'type', 'icon', ['icon_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'type', type_='foreignkey')
    op.drop_column('type', 'icon_id')
    # ### end Alembic commands ###
