"""Add Icon and Header ids to Resource

Revision ID: d4bc1e380bc8
Revises: 59a8d290f4d0
Create Date: 2018-06-27 10:21:47.996225

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd4bc1e380bc8'
down_revision = '59a8d290f4d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resource', sa.Column('header_id', sa.String(), nullable=True))
    op.add_column('resource', sa.Column('icon_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('resource', 'icon_id')
    op.drop_column('resource', 'header_id')
    # ### end Alembic commands ###
