"""empty message

Revision ID: ed20c3206460
Revises: 8a0e295af33c
Create Date: 2018-07-18 12:08:54.854137

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
from alembic.ddl import postgresql

revision = 'ed20c3206460'
down_revision = '8a0e295af33c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('resource', 'approved')
    op.add_column('resource', sa.Column('approved', sa.String(), nullable=False, default="unapproved"))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('resource', 'approved')
    op.add_column('resource', sa.Column('approved', sa.Boolean(), nullable=False, default=False))
    # ### end Alembic commands ###

